#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ECURRHH911")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbl_Cargo_Institucional(Tbl_Cargo_Institucional instance);
    partial void UpdateTbl_Cargo_Institucional(Tbl_Cargo_Institucional instance);
    partial void DeleteTbl_Cargo_Institucional(Tbl_Cargo_Institucional instance);
    partial void InsertTbl_Personas(Tbl_Personas instance);
    partial void UpdateTbl_Personas(Tbl_Personas instance);
    partial void DeleteTbl_Personas(Tbl_Personas instance);
    partial void InsertTbl_Contratos(Tbl_Contratos instance);
    partial void UpdateTbl_Contratos(Tbl_Contratos instance);
    partial void DeleteTbl_Contratos(Tbl_Contratos instance);
    partial void InsertTbl_Estructuras(Tbl_Estructuras instance);
    partial void UpdateTbl_Estructuras(Tbl_Estructuras instance);
    partial void DeleteTbl_Estructuras(Tbl_Estructuras instance);
    partial void InsertTbl_Partida_General(Tbl_Partida_General instance);
    partial void UpdateTbl_Partida_General(Tbl_Partida_General instance);
    partial void DeleteTbl_Partida_General(Tbl_Partida_General instance);
    partial void InsertTbl_Partida_Individual(Tbl_Partida_Individual instance);
    partial void UpdateTbl_Partida_Individual(Tbl_Partida_Individual instance);
    partial void DeleteTbl_Partida_Individual(Tbl_Partida_Individual instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.ECURRHH911ConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Tbl_Cargo_Institucional> Tbl_Cargo_Institucional
		{
			get
			{
				return this.GetTable<Tbl_Cargo_Institucional>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Personas> Tbl_Personas
		{
			get
			{
				return this.GetTable<Tbl_Personas>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Comision_Servicios> Tbl_Comision_Servicios
		{
			get
			{
				return this.GetTable<Tbl_Comision_Servicios>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Contratos> Tbl_Contratos
		{
			get
			{
				return this.GetTable<Tbl_Contratos>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Datos_Institucionales> Tbl_Datos_Institucionales
		{
			get
			{
				return this.GetTable<Tbl_Datos_Institucionales>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Estructuras> Tbl_Estructuras
		{
			get
			{
				return this.GetTable<Tbl_Estructuras>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Partida_General> Tbl_Partida_General
		{
			get
			{
				return this.GetTable<Tbl_Partida_General>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Partida_Individual> Tbl_Partida_Individual
		{
			get
			{
				return this.GetTable<Tbl_Partida_Individual>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Listar_Estado_Activo_Cargo_Institucional")]
		public ISingleResult<Listar_Estado_Activo_Cargo_InstitucionalResult> Listar_Estado_Activo_Cargo_Institucional()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Listar_Estado_Activo_Cargo_InstitucionalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Registro_Partida_Individual")]
		public int Registro_Partida_Individual([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero_Partida_Individual", DbType="Int")] System.Nullable<int> numero_Partida_Individual)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero_Partida_Individual);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Listar_Estado_Activo_Partida_General")]
		public ISingleResult<Listar_Estado_Activo_Partida_GeneralResult> Listar_Estado_Activo_Partida_General()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Listar_Estado_Activo_Partida_GeneralResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Listar_Partida_Individual")]
		public ISingleResult<Listar_Partida_IndividualResult> Listar_Partida_Individual()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Listar_Partida_IndividualResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Registro_Cargo_Institucional")]
		public int Registro_Cargo_Institucional([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nom_Cargo", DbType="VarChar(50)")] string nom_Cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_General", DbType="Int")] System.Nullable<int> id_General, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Estado_Cargo", DbType="VarChar(1)")] string estado_Cargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nom_Cargo, id_General, estado_Cargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Registro_Partida_General")]
		public int Registro_Partida_General([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Numero_Partida_General", DbType="Int")] System.Nullable<int> numero_Partida_General, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Partida_General_estado", DbType="VarChar(1)")] string partida_General_estado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), numero_Partida_General, partida_General_estado);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Cargo_Institucional")]
	public partial class Tbl_Cargo_Institucional : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Cargo_Institucional;
		
		private string _Nom_Cargo_Institucional;
		
		private System.Nullable<int> _Id_Partida_Individual;
		
		private System.Nullable<int> _Id_Partida_General;
		
		private string _Estado_Cargo_Institucional;
		
		private EntitySet<Tbl_Personas> _Tbl_Personas;
		
		private EntityRef<Tbl_Partida_General> _Tbl_Partida_General;
		
		private EntityRef<Tbl_Partida_Individual> _Tbl_Partida_Individual;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Cargo_InstitucionalChanging(int value);
    partial void OnId_Cargo_InstitucionalChanged();
    partial void OnNom_Cargo_InstitucionalChanging(string value);
    partial void OnNom_Cargo_InstitucionalChanged();
    partial void OnId_Partida_IndividualChanging(System.Nullable<int> value);
    partial void OnId_Partida_IndividualChanged();
    partial void OnId_Partida_GeneralChanging(System.Nullable<int> value);
    partial void OnId_Partida_GeneralChanged();
    partial void OnEstado_Cargo_InstitucionalChanging(string value);
    partial void OnEstado_Cargo_InstitucionalChanged();
    #endregion
		
		public Tbl_Cargo_Institucional()
		{
			this._Tbl_Personas = new EntitySet<Tbl_Personas>(new Action<Tbl_Personas>(this.attach_Tbl_Personas), new Action<Tbl_Personas>(this.detach_Tbl_Personas));
			this._Tbl_Partida_General = default(EntityRef<Tbl_Partida_General>);
			this._Tbl_Partida_Individual = default(EntityRef<Tbl_Partida_Individual>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cargo_Institucional", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Cargo_Institucional
		{
			get
			{
				return this._Id_Cargo_Institucional;
			}
			set
			{
				if ((this._Id_Cargo_Institucional != value))
				{
					this.OnId_Cargo_InstitucionalChanging(value);
					this.SendPropertyChanging();
					this._Id_Cargo_Institucional = value;
					this.SendPropertyChanged("Id_Cargo_Institucional");
					this.OnId_Cargo_InstitucionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Cargo_Institucional", DbType="VarChar(50)")]
		public string Nom_Cargo_Institucional
		{
			get
			{
				return this._Nom_Cargo_Institucional;
			}
			set
			{
				if ((this._Nom_Cargo_Institucional != value))
				{
					this.OnNom_Cargo_InstitucionalChanging(value);
					this.SendPropertyChanging();
					this._Nom_Cargo_Institucional = value;
					this.SendPropertyChanged("Nom_Cargo_Institucional");
					this.OnNom_Cargo_InstitucionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_Individual", DbType="Int")]
		public System.Nullable<int> Id_Partida_Individual
		{
			get
			{
				return this._Id_Partida_Individual;
			}
			set
			{
				if ((this._Id_Partida_Individual != value))
				{
					if (this._Tbl_Partida_Individual.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_Partida_IndividualChanging(value);
					this.SendPropertyChanging();
					this._Id_Partida_Individual = value;
					this.SendPropertyChanged("Id_Partida_Individual");
					this.OnId_Partida_IndividualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_General", DbType="Int")]
		public System.Nullable<int> Id_Partida_General
		{
			get
			{
				return this._Id_Partida_General;
			}
			set
			{
				if ((this._Id_Partida_General != value))
				{
					if (this._Tbl_Partida_General.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_Partida_GeneralChanging(value);
					this.SendPropertyChanging();
					this._Id_Partida_General = value;
					this.SendPropertyChanged("Id_Partida_General");
					this.OnId_Partida_GeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Cargo_Institucional", DbType="VarChar(1)")]
		public string Estado_Cargo_Institucional
		{
			get
			{
				return this._Estado_Cargo_Institucional;
			}
			set
			{
				if ((this._Estado_Cargo_Institucional != value))
				{
					this.OnEstado_Cargo_InstitucionalChanging(value);
					this.SendPropertyChanging();
					this._Estado_Cargo_Institucional = value;
					this.SendPropertyChanged("Estado_Cargo_Institucional");
					this.OnEstado_Cargo_InstitucionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cargo_Institucional_Tbl_Personas", Storage="_Tbl_Personas", ThisKey="Id_Cargo_Institucional", OtherKey="Partida_Individual")]
		public EntitySet<Tbl_Personas> Tbl_Personas
		{
			get
			{
				return this._Tbl_Personas;
			}
			set
			{
				this._Tbl_Personas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Partida_General_Tbl_Cargo_Institucional", Storage="_Tbl_Partida_General", ThisKey="Id_Partida_General", OtherKey="Id_Partida_General", IsForeignKey=true)]
		public Tbl_Partida_General Tbl_Partida_General
		{
			get
			{
				return this._Tbl_Partida_General.Entity;
			}
			set
			{
				Tbl_Partida_General previousValue = this._Tbl_Partida_General.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Partida_General.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Partida_General.Entity = null;
						previousValue.Tbl_Cargo_Institucional.Remove(this);
					}
					this._Tbl_Partida_General.Entity = value;
					if ((value != null))
					{
						value.Tbl_Cargo_Institucional.Add(this);
						this._Id_Partida_General = value.Id_Partida_General;
					}
					else
					{
						this._Id_Partida_General = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Partida_General");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Partida_Individual_Tbl_Cargo_Institucional", Storage="_Tbl_Partida_Individual", ThisKey="Id_Partida_Individual", OtherKey="Id_Partida_Individual", IsForeignKey=true)]
		public Tbl_Partida_Individual Tbl_Partida_Individual
		{
			get
			{
				return this._Tbl_Partida_Individual.Entity;
			}
			set
			{
				Tbl_Partida_Individual previousValue = this._Tbl_Partida_Individual.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Partida_Individual.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Partida_Individual.Entity = null;
						previousValue.Tbl_Cargo_Institucional.Remove(this);
					}
					this._Tbl_Partida_Individual.Entity = value;
					if ((value != null))
					{
						value.Tbl_Cargo_Institucional.Add(this);
						this._Id_Partida_Individual = value.Id_Partida_Individual;
					}
					else
					{
						this._Id_Partida_Individual = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Partida_Individual");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Personas(Tbl_Personas entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cargo_Institucional = this;
		}
		
		private void detach_Tbl_Personas(Tbl_Personas entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Cargo_Institucional = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Personas")]
	public partial class Tbl_Personas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Persona_Cedula;
		
		private string _Primer_Nombre;
		
		private string _Segundo_Nombre;
		
		private string _Primer_Apellido;
		
		private string _Segundo_Apellido;
		
		private System.Nullable<System.DateTime> _Fecha_Nacimiento;
		
		private string _Genero;
		
		private string _Correo_Personal;
		
		private System.Nullable<int> _Num_Celular;
		
		private string _Dirrecion_Domicilio;
		
		private System.Nullable<int> _Partida_Individual;
		
		private string _Observaciones;
		
		private string _Proceso_Interno;
		
		private string _Estado_persona;
		
		private EntitySet<Tbl_Contratos> _Tbl_Contratos;
		
		private EntityRef<Tbl_Cargo_Institucional> _Tbl_Cargo_Institucional;
		
		private EntityRef<Tbl_Estructuras> _Tbl_Estructuras;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPersona_CedulaChanging(int value);
    partial void OnPersona_CedulaChanged();
    partial void OnPrimer_NombreChanging(string value);
    partial void OnPrimer_NombreChanged();
    partial void OnSegundo_NombreChanging(string value);
    partial void OnSegundo_NombreChanged();
    partial void OnPrimer_ApellidoChanging(string value);
    partial void OnPrimer_ApellidoChanged();
    partial void OnSegundo_ApellidoChanging(string value);
    partial void OnSegundo_ApellidoChanged();
    partial void OnFecha_NacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_NacimientoChanged();
    partial void OnGeneroChanging(string value);
    partial void OnGeneroChanged();
    partial void OnCorreo_PersonalChanging(string value);
    partial void OnCorreo_PersonalChanged();
    partial void OnNum_CelularChanging(System.Nullable<int> value);
    partial void OnNum_CelularChanged();
    partial void OnDirrecion_DomicilioChanging(string value);
    partial void OnDirrecion_DomicilioChanged();
    partial void OnPartida_IndividualChanging(System.Nullable<int> value);
    partial void OnPartida_IndividualChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnProceso_InternoChanging(string value);
    partial void OnProceso_InternoChanged();
    partial void OnEstado_personaChanging(string value);
    partial void OnEstado_personaChanged();
    #endregion
		
		public Tbl_Personas()
		{
			this._Tbl_Contratos = new EntitySet<Tbl_Contratos>(new Action<Tbl_Contratos>(this.attach_Tbl_Contratos), new Action<Tbl_Contratos>(this.detach_Tbl_Contratos));
			this._Tbl_Cargo_Institucional = default(EntityRef<Tbl_Cargo_Institucional>);
			this._Tbl_Estructuras = default(EntityRef<Tbl_Estructuras>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Cedula", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Persona_Cedula
		{
			get
			{
				return this._Persona_Cedula;
			}
			set
			{
				if ((this._Persona_Cedula != value))
				{
					this.OnPersona_CedulaChanging(value);
					this.SendPropertyChanging();
					this._Persona_Cedula = value;
					this.SendPropertyChanged("Persona_Cedula");
					this.OnPersona_CedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Nombre", DbType="VarChar(20)")]
		public string Primer_Nombre
		{
			get
			{
				return this._Primer_Nombre;
			}
			set
			{
				if ((this._Primer_Nombre != value))
				{
					this.OnPrimer_NombreChanging(value);
					this.SendPropertyChanging();
					this._Primer_Nombre = value;
					this.SendPropertyChanged("Primer_Nombre");
					this.OnPrimer_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Nombre", DbType="VarChar(20)")]
		public string Segundo_Nombre
		{
			get
			{
				return this._Segundo_Nombre;
			}
			set
			{
				if ((this._Segundo_Nombre != value))
				{
					this.OnSegundo_NombreChanging(value);
					this.SendPropertyChanging();
					this._Segundo_Nombre = value;
					this.SendPropertyChanged("Segundo_Nombre");
					this.OnSegundo_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Apellido", DbType="VarChar(20)")]
		public string Primer_Apellido
		{
			get
			{
				return this._Primer_Apellido;
			}
			set
			{
				if ((this._Primer_Apellido != value))
				{
					this.OnPrimer_ApellidoChanging(value);
					this.SendPropertyChanging();
					this._Primer_Apellido = value;
					this.SendPropertyChanged("Primer_Apellido");
					this.OnPrimer_ApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Segundo_Apellido", DbType="VarChar(20)")]
		public string Segundo_Apellido
		{
			get
			{
				return this._Segundo_Apellido;
			}
			set
			{
				if ((this._Segundo_Apellido != value))
				{
					this.OnSegundo_ApellidoChanging(value);
					this.SendPropertyChanging();
					this._Segundo_Apellido = value;
					this.SendPropertyChanged("Segundo_Apellido");
					this.OnSegundo_ApellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this.OnFecha_NacimientoChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Nacimiento = value;
					this.SendPropertyChanged("Fecha_Nacimiento");
					this.OnFecha_NacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genero", DbType="VarChar(1)")]
		public string Genero
		{
			get
			{
				return this._Genero;
			}
			set
			{
				if ((this._Genero != value))
				{
					this.OnGeneroChanging(value);
					this.SendPropertyChanging();
					this._Genero = value;
					this.SendPropertyChanged("Genero");
					this.OnGeneroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Personal", DbType="VarChar(20)")]
		public string Correo_Personal
		{
			get
			{
				return this._Correo_Personal;
			}
			set
			{
				if ((this._Correo_Personal != value))
				{
					this.OnCorreo_PersonalChanging(value);
					this.SendPropertyChanging();
					this._Correo_Personal = value;
					this.SendPropertyChanged("Correo_Personal");
					this.OnCorreo_PersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Celular", DbType="Int")]
		public System.Nullable<int> Num_Celular
		{
			get
			{
				return this._Num_Celular;
			}
			set
			{
				if ((this._Num_Celular != value))
				{
					this.OnNum_CelularChanging(value);
					this.SendPropertyChanging();
					this._Num_Celular = value;
					this.SendPropertyChanged("Num_Celular");
					this.OnNum_CelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirrecion_Domicilio", DbType="VarChar(25)")]
		public string Dirrecion_Domicilio
		{
			get
			{
				return this._Dirrecion_Domicilio;
			}
			set
			{
				if ((this._Dirrecion_Domicilio != value))
				{
					this.OnDirrecion_DomicilioChanging(value);
					this.SendPropertyChanging();
					this._Dirrecion_Domicilio = value;
					this.SendPropertyChanged("Dirrecion_Domicilio");
					this.OnDirrecion_DomicilioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Partida_Individual", DbType="Int")]
		public System.Nullable<int> Partida_Individual
		{
			get
			{
				return this._Partida_Individual;
			}
			set
			{
				if ((this._Partida_Individual != value))
				{
					if (this._Tbl_Cargo_Institucional.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPartida_IndividualChanging(value);
					this.SendPropertyChanging();
					this._Partida_Individual = value;
					this.SendPropertyChanged("Partida_Individual");
					this.OnPartida_IndividualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="VarChar(100)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proceso_Interno", DbType="VarChar(50)")]
		public string Proceso_Interno
		{
			get
			{
				return this._Proceso_Interno;
			}
			set
			{
				if ((this._Proceso_Interno != value))
				{
					if (this._Tbl_Estructuras.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnProceso_InternoChanging(value);
					this.SendPropertyChanging();
					this._Proceso_Interno = value;
					this.SendPropertyChanged("Proceso_Interno");
					this.OnProceso_InternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_persona", DbType="VarChar(1)")]
		public string Estado_persona
		{
			get
			{
				return this._Estado_persona;
			}
			set
			{
				if ((this._Estado_persona != value))
				{
					this.OnEstado_personaChanging(value);
					this.SendPropertyChanging();
					this._Estado_persona = value;
					this.SendPropertyChanged("Estado_persona");
					this.OnEstado_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Personas_Tbl_Contratos", Storage="_Tbl_Contratos", ThisKey="Persona_Cedula", OtherKey="Persona_Cedula")]
		public EntitySet<Tbl_Contratos> Tbl_Contratos
		{
			get
			{
				return this._Tbl_Contratos;
			}
			set
			{
				this._Tbl_Contratos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Cargo_Institucional_Tbl_Personas", Storage="_Tbl_Cargo_Institucional", ThisKey="Partida_Individual", OtherKey="Id_Cargo_Institucional", IsForeignKey=true)]
		public Tbl_Cargo_Institucional Tbl_Cargo_Institucional
		{
			get
			{
				return this._Tbl_Cargo_Institucional.Entity;
			}
			set
			{
				Tbl_Cargo_Institucional previousValue = this._Tbl_Cargo_Institucional.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Cargo_Institucional.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Cargo_Institucional.Entity = null;
						previousValue.Tbl_Personas.Remove(this);
					}
					this._Tbl_Cargo_Institucional.Entity = value;
					if ((value != null))
					{
						value.Tbl_Personas.Add(this);
						this._Partida_Individual = value.Id_Cargo_Institucional;
					}
					else
					{
						this._Partida_Individual = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Cargo_Institucional");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Estructuras_Tbl_Personas", Storage="_Tbl_Estructuras", ThisKey="Proceso_Interno", OtherKey="Proceso_Interno", IsForeignKey=true)]
		public Tbl_Estructuras Tbl_Estructuras
		{
			get
			{
				return this._Tbl_Estructuras.Entity;
			}
			set
			{
				Tbl_Estructuras previousValue = this._Tbl_Estructuras.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Estructuras.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Estructuras.Entity = null;
						previousValue.Tbl_Personas.Remove(this);
					}
					this._Tbl_Estructuras.Entity = value;
					if ((value != null))
					{
						value.Tbl_Personas.Add(this);
						this._Proceso_Interno = value.Proceso_Interno;
					}
					else
					{
						this._Proceso_Interno = default(string);
					}
					this.SendPropertyChanged("Tbl_Estructuras");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Contratos(Tbl_Contratos entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Personas = this;
		}
		
		private void detach_Tbl_Contratos(Tbl_Contratos entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Personas = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Comision_Servicios")]
	public partial class Tbl_Comision_Servicios
	{
		
		private string _Numero_Contrato;
		
		private string _Origen_Comision;
		
		private System.Nullable<System.DateTime> _Fecha_Inicio_Comi;
		
		private System.Nullable<System.DateTime> _Fecha_Fin_Comi;
		
		public Tbl_Comision_Servicios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Contrato", DbType="VarChar(50)")]
		public string Numero_Contrato
		{
			get
			{
				return this._Numero_Contrato;
			}
			set
			{
				if ((this._Numero_Contrato != value))
				{
					this._Numero_Contrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Origen_Comision", DbType="VarChar(100)")]
		public string Origen_Comision
		{
			get
			{
				return this._Origen_Comision;
			}
			set
			{
				if ((this._Origen_Comision != value))
				{
					this._Origen_Comision = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inicio_Comi", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Inicio_Comi
		{
			get
			{
				return this._Fecha_Inicio_Comi;
			}
			set
			{
				if ((this._Fecha_Inicio_Comi != value))
				{
					this._Fecha_Inicio_Comi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Fin_Comi", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Fin_Comi
		{
			get
			{
				return this._Fecha_Fin_Comi;
			}
			set
			{
				if ((this._Fecha_Fin_Comi != value))
				{
					this._Fecha_Fin_Comi = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Contratos")]
	public partial class Tbl_Contratos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Numero_Contrato;
		
		private System.Nullable<int> _Persona_Cedula;
		
		private System.Nullable<System.DateTime> _Fecha_Inicio;
		
		private System.Nullable<System.DateTime> _Fecha_Fin;
		
		private string _Motivo_Salida;
		
		private System.Nullable<int> _Anios_Experiencia;
		
		private string _Modalidad_Laboral;
		
		private string _Instruccion_Formal;
		
		private string _Contrato_Estado;
		
		private System.Nullable<int> _RMU;
		
		private string _Grado;
		
		private string _Grupo_Ocupacional;
		
		private string _Estado_Contrato;
		
		private EntityRef<Tbl_Personas> _Tbl_Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNumero_ContratoChanging(string value);
    partial void OnNumero_ContratoChanged();
    partial void OnPersona_CedulaChanging(System.Nullable<int> value);
    partial void OnPersona_CedulaChanged();
    partial void OnFecha_InicioChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_InicioChanged();
    partial void OnFecha_FinChanging(System.Nullable<System.DateTime> value);
    partial void OnFecha_FinChanged();
    partial void OnMotivo_SalidaChanging(string value);
    partial void OnMotivo_SalidaChanged();
    partial void OnAnios_ExperienciaChanging(System.Nullable<int> value);
    partial void OnAnios_ExperienciaChanged();
    partial void OnModalidad_LaboralChanging(string value);
    partial void OnModalidad_LaboralChanged();
    partial void OnInstruccion_FormalChanging(string value);
    partial void OnInstruccion_FormalChanged();
    partial void OnContrato_EstadoChanging(string value);
    partial void OnContrato_EstadoChanged();
    partial void OnRMUChanging(System.Nullable<int> value);
    partial void OnRMUChanged();
    partial void OnGradoChanging(string value);
    partial void OnGradoChanged();
    partial void OnGrupo_OcupacionalChanging(string value);
    partial void OnGrupo_OcupacionalChanged();
    partial void OnEstado_ContratoChanging(string value);
    partial void OnEstado_ContratoChanged();
    #endregion
		
		public Tbl_Contratos()
		{
			this._Tbl_Personas = default(EntityRef<Tbl_Personas>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Contrato", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Numero_Contrato
		{
			get
			{
				return this._Numero_Contrato;
			}
			set
			{
				if ((this._Numero_Contrato != value))
				{
					this.OnNumero_ContratoChanging(value);
					this.SendPropertyChanging();
					this._Numero_Contrato = value;
					this.SendPropertyChanged("Numero_Contrato");
					this.OnNumero_ContratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Cedula", DbType="Int")]
		public System.Nullable<int> Persona_Cedula
		{
			get
			{
				return this._Persona_Cedula;
			}
			set
			{
				if ((this._Persona_Cedula != value))
				{
					if (this._Tbl_Personas.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersona_CedulaChanging(value);
					this.SendPropertyChanging();
					this._Persona_Cedula = value;
					this.SendPropertyChanged("Persona_Cedula");
					this.OnPersona_CedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Inicio", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Inicio
		{
			get
			{
				return this._Fecha_Inicio;
			}
			set
			{
				if ((this._Fecha_Inicio != value))
				{
					this.OnFecha_InicioChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Inicio = value;
					this.SendPropertyChanged("Fecha_Inicio");
					this.OnFecha_InicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Fin", DbType="Date")]
		public System.Nullable<System.DateTime> Fecha_Fin
		{
			get
			{
				return this._Fecha_Fin;
			}
			set
			{
				if ((this._Fecha_Fin != value))
				{
					this.OnFecha_FinChanging(value);
					this.SendPropertyChanging();
					this._Fecha_Fin = value;
					this.SendPropertyChanged("Fecha_Fin");
					this.OnFecha_FinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Motivo_Salida", DbType="VarChar(50)")]
		public string Motivo_Salida
		{
			get
			{
				return this._Motivo_Salida;
			}
			set
			{
				if ((this._Motivo_Salida != value))
				{
					this.OnMotivo_SalidaChanging(value);
					this.SendPropertyChanging();
					this._Motivo_Salida = value;
					this.SendPropertyChanged("Motivo_Salida");
					this.OnMotivo_SalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anios_Experiencia", DbType="Int")]
		public System.Nullable<int> Anios_Experiencia
		{
			get
			{
				return this._Anios_Experiencia;
			}
			set
			{
				if ((this._Anios_Experiencia != value))
				{
					this.OnAnios_ExperienciaChanging(value);
					this.SendPropertyChanging();
					this._Anios_Experiencia = value;
					this.SendPropertyChanged("Anios_Experiencia");
					this.OnAnios_ExperienciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modalidad_Laboral", DbType="VarChar(100)")]
		public string Modalidad_Laboral
		{
			get
			{
				return this._Modalidad_Laboral;
			}
			set
			{
				if ((this._Modalidad_Laboral != value))
				{
					this.OnModalidad_LaboralChanging(value);
					this.SendPropertyChanging();
					this._Modalidad_Laboral = value;
					this.SendPropertyChanged("Modalidad_Laboral");
					this.OnModalidad_LaboralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Instruccion_Formal", DbType="VarChar(25)")]
		public string Instruccion_Formal
		{
			get
			{
				return this._Instruccion_Formal;
			}
			set
			{
				if ((this._Instruccion_Formal != value))
				{
					this.OnInstruccion_FormalChanging(value);
					this.SendPropertyChanging();
					this._Instruccion_Formal = value;
					this.SendPropertyChanged("Instruccion_Formal");
					this.OnInstruccion_FormalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrato_Estado", DbType="VarChar(1)")]
		public string Contrato_Estado
		{
			get
			{
				return this._Contrato_Estado;
			}
			set
			{
				if ((this._Contrato_Estado != value))
				{
					this.OnContrato_EstadoChanging(value);
					this.SendPropertyChanging();
					this._Contrato_Estado = value;
					this.SendPropertyChanged("Contrato_Estado");
					this.OnContrato_EstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMU", DbType="Int")]
		public System.Nullable<int> RMU
		{
			get
			{
				return this._RMU;
			}
			set
			{
				if ((this._RMU != value))
				{
					this.OnRMUChanging(value);
					this.SendPropertyChanging();
					this._RMU = value;
					this.SendPropertyChanged("RMU");
					this.OnRMUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grado", DbType="VarChar(10)")]
		public string Grado
		{
			get
			{
				return this._Grado;
			}
			set
			{
				if ((this._Grado != value))
				{
					this.OnGradoChanging(value);
					this.SendPropertyChanging();
					this._Grado = value;
					this.SendPropertyChanged("Grado");
					this.OnGradoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupo_Ocupacional", DbType="VarChar(25)")]
		public string Grupo_Ocupacional
		{
			get
			{
				return this._Grupo_Ocupacional;
			}
			set
			{
				if ((this._Grupo_Ocupacional != value))
				{
					this.OnGrupo_OcupacionalChanging(value);
					this.SendPropertyChanging();
					this._Grupo_Ocupacional = value;
					this.SendPropertyChanged("Grupo_Ocupacional");
					this.OnGrupo_OcupacionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Contrato", DbType="VarChar(1)")]
		public string Estado_Contrato
		{
			get
			{
				return this._Estado_Contrato;
			}
			set
			{
				if ((this._Estado_Contrato != value))
				{
					this.OnEstado_ContratoChanging(value);
					this.SendPropertyChanging();
					this._Estado_Contrato = value;
					this.SendPropertyChanged("Estado_Contrato");
					this.OnEstado_ContratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Personas_Tbl_Contratos", Storage="_Tbl_Personas", ThisKey="Persona_Cedula", OtherKey="Persona_Cedula", IsForeignKey=true)]
		public Tbl_Personas Tbl_Personas
		{
			get
			{
				return this._Tbl_Personas.Entity;
			}
			set
			{
				Tbl_Personas previousValue = this._Tbl_Personas.Entity;
				if (((previousValue != value) 
							|| (this._Tbl_Personas.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tbl_Personas.Entity = null;
						previousValue.Tbl_Contratos.Remove(this);
					}
					this._Tbl_Personas.Entity = value;
					if ((value != null))
					{
						value.Tbl_Contratos.Add(this);
						this._Persona_Cedula = value.Persona_Cedula;
					}
					else
					{
						this._Persona_Cedula = default(Nullable<int>);
					}
					this.SendPropertyChanged("Tbl_Personas");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Datos_Institucionales")]
	public partial class Tbl_Datos_Institucionales
	{
		
		private System.Nullable<int> _Persona_Cedula;
		
		private string _Dirreccion_Institucional;
		
		private string _Correo_Institucional;
		
		private System.Nullable<int> _Telefono_Institucional;
		
		private System.Nullable<int> _Extension_Telf;
		
		private string _Zona;
		
		private string _Sede;
		
		public Tbl_Datos_Institucionales()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_Cedula", DbType="Int")]
		public System.Nullable<int> Persona_Cedula
		{
			get
			{
				return this._Persona_Cedula;
			}
			set
			{
				if ((this._Persona_Cedula != value))
				{
					this._Persona_Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dirreccion_Institucional", DbType="VarChar(100)")]
		public string Dirreccion_Institucional
		{
			get
			{
				return this._Dirreccion_Institucional;
			}
			set
			{
				if ((this._Dirreccion_Institucional != value))
				{
					this._Dirreccion_Institucional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo_Institucional", DbType="VarChar(50)")]
		public string Correo_Institucional
		{
			get
			{
				return this._Correo_Institucional;
			}
			set
			{
				if ((this._Correo_Institucional != value))
				{
					this._Correo_Institucional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono_Institucional", DbType="Int")]
		public System.Nullable<int> Telefono_Institucional
		{
			get
			{
				return this._Telefono_Institucional;
			}
			set
			{
				if ((this._Telefono_Institucional != value))
				{
					this._Telefono_Institucional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Extension_Telf", DbType="Int")]
		public System.Nullable<int> Extension_Telf
		{
			get
			{
				return this._Extension_Telf;
			}
			set
			{
				if ((this._Extension_Telf != value))
				{
					this._Extension_Telf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zona", DbType="VarChar(25)")]
		public string Zona
		{
			get
			{
				return this._Zona;
			}
			set
			{
				if ((this._Zona != value))
				{
					this._Zona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sede", DbType="VarChar(25)")]
		public string Sede
		{
			get
			{
				return this._Sede;
			}
			set
			{
				if ((this._Sede != value))
				{
					this._Sede = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Estructuras")]
	public partial class Tbl_Estructuras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Proceso_Interno;
		
		private string _Estrcutura_Tres;
		
		private string _Estructura_Dos;
		
		private string _Estructura_Uno;
		
		private EntitySet<Tbl_Personas> _Tbl_Personas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProceso_InternoChanging(string value);
    partial void OnProceso_InternoChanged();
    partial void OnEstrcutura_TresChanging(string value);
    partial void OnEstrcutura_TresChanged();
    partial void OnEstructura_DosChanging(string value);
    partial void OnEstructura_DosChanged();
    partial void OnEstructura_UnoChanging(string value);
    partial void OnEstructura_UnoChanged();
    #endregion
		
		public Tbl_Estructuras()
		{
			this._Tbl_Personas = new EntitySet<Tbl_Personas>(new Action<Tbl_Personas>(this.attach_Tbl_Personas), new Action<Tbl_Personas>(this.detach_Tbl_Personas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proceso_Interno", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Proceso_Interno
		{
			get
			{
				return this._Proceso_Interno;
			}
			set
			{
				if ((this._Proceso_Interno != value))
				{
					this.OnProceso_InternoChanging(value);
					this.SendPropertyChanging();
					this._Proceso_Interno = value;
					this.SendPropertyChanged("Proceso_Interno");
					this.OnProceso_InternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estrcutura_Tres", DbType="VarChar(50)")]
		public string Estrcutura_Tres
		{
			get
			{
				return this._Estrcutura_Tres;
			}
			set
			{
				if ((this._Estrcutura_Tres != value))
				{
					this.OnEstrcutura_TresChanging(value);
					this.SendPropertyChanging();
					this._Estrcutura_Tres = value;
					this.SendPropertyChanged("Estrcutura_Tres");
					this.OnEstrcutura_TresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estructura_Dos", DbType="VarChar(50)")]
		public string Estructura_Dos
		{
			get
			{
				return this._Estructura_Dos;
			}
			set
			{
				if ((this._Estructura_Dos != value))
				{
					this.OnEstructura_DosChanging(value);
					this.SendPropertyChanging();
					this._Estructura_Dos = value;
					this.SendPropertyChanged("Estructura_Dos");
					this.OnEstructura_DosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estructura_Uno", DbType="VarChar(50)")]
		public string Estructura_Uno
		{
			get
			{
				return this._Estructura_Uno;
			}
			set
			{
				if ((this._Estructura_Uno != value))
				{
					this.OnEstructura_UnoChanging(value);
					this.SendPropertyChanging();
					this._Estructura_Uno = value;
					this.SendPropertyChanged("Estructura_Uno");
					this.OnEstructura_UnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Estructuras_Tbl_Personas", Storage="_Tbl_Personas", ThisKey="Proceso_Interno", OtherKey="Proceso_Interno")]
		public EntitySet<Tbl_Personas> Tbl_Personas
		{
			get
			{
				return this._Tbl_Personas;
			}
			set
			{
				this._Tbl_Personas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Personas(Tbl_Personas entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Estructuras = this;
		}
		
		private void detach_Tbl_Personas(Tbl_Personas entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Estructuras = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Partida_General")]
	public partial class Tbl_Partida_General : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Partida_General;
		
		private System.Nullable<int> _Numero_Partida_General;
		
		private string _Estado_Partida_General;
		
		private EntitySet<Tbl_Cargo_Institucional> _Tbl_Cargo_Institucional;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Partida_GeneralChanging(int value);
    partial void OnId_Partida_GeneralChanged();
    partial void OnNumero_Partida_GeneralChanging(System.Nullable<int> value);
    partial void OnNumero_Partida_GeneralChanged();
    partial void OnEstado_Partida_GeneralChanging(string value);
    partial void OnEstado_Partida_GeneralChanged();
    #endregion
		
		public Tbl_Partida_General()
		{
			this._Tbl_Cargo_Institucional = new EntitySet<Tbl_Cargo_Institucional>(new Action<Tbl_Cargo_Institucional>(this.attach_Tbl_Cargo_Institucional), new Action<Tbl_Cargo_Institucional>(this.detach_Tbl_Cargo_Institucional));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_General", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Partida_General
		{
			get
			{
				return this._Id_Partida_General;
			}
			set
			{
				if ((this._Id_Partida_General != value))
				{
					this.OnId_Partida_GeneralChanging(value);
					this.SendPropertyChanging();
					this._Id_Partida_General = value;
					this.SendPropertyChanged("Id_Partida_General");
					this.OnId_Partida_GeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Partida_General", DbType="Int")]
		public System.Nullable<int> Numero_Partida_General
		{
			get
			{
				return this._Numero_Partida_General;
			}
			set
			{
				if ((this._Numero_Partida_General != value))
				{
					this.OnNumero_Partida_GeneralChanging(value);
					this.SendPropertyChanging();
					this._Numero_Partida_General = value;
					this.SendPropertyChanged("Numero_Partida_General");
					this.OnNumero_Partida_GeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Partida_General", DbType="VarChar(1)")]
		public string Estado_Partida_General
		{
			get
			{
				return this._Estado_Partida_General;
			}
			set
			{
				if ((this._Estado_Partida_General != value))
				{
					this.OnEstado_Partida_GeneralChanging(value);
					this.SendPropertyChanging();
					this._Estado_Partida_General = value;
					this.SendPropertyChanged("Estado_Partida_General");
					this.OnEstado_Partida_GeneralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Partida_General_Tbl_Cargo_Institucional", Storage="_Tbl_Cargo_Institucional", ThisKey="Id_Partida_General", OtherKey="Id_Partida_General")]
		public EntitySet<Tbl_Cargo_Institucional> Tbl_Cargo_Institucional
		{
			get
			{
				return this._Tbl_Cargo_Institucional;
			}
			set
			{
				this._Tbl_Cargo_Institucional.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Cargo_Institucional(Tbl_Cargo_Institucional entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Partida_General = this;
		}
		
		private void detach_Tbl_Cargo_Institucional(Tbl_Cargo_Institucional entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Partida_General = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Partida_Individual")]
	public partial class Tbl_Partida_Individual : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id_Partida_Individual;
		
		private System.Nullable<int> _Num_Partida_Individual;
		
		private EntitySet<Tbl_Cargo_Institucional> _Tbl_Cargo_Institucional;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_Partida_IndividualChanging(int value);
    partial void OnId_Partida_IndividualChanged();
    partial void OnNum_Partida_IndividualChanging(System.Nullable<int> value);
    partial void OnNum_Partida_IndividualChanged();
    #endregion
		
		public Tbl_Partida_Individual()
		{
			this._Tbl_Cargo_Institucional = new EntitySet<Tbl_Cargo_Institucional>(new Action<Tbl_Cargo_Institucional>(this.attach_Tbl_Cargo_Institucional), new Action<Tbl_Cargo_Institucional>(this.detach_Tbl_Cargo_Institucional));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_Individual", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id_Partida_Individual
		{
			get
			{
				return this._Id_Partida_Individual;
			}
			set
			{
				if ((this._Id_Partida_Individual != value))
				{
					this.OnId_Partida_IndividualChanging(value);
					this.SendPropertyChanging();
					this._Id_Partida_Individual = value;
					this.SendPropertyChanged("Id_Partida_Individual");
					this.OnId_Partida_IndividualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Partida_Individual", DbType="Int")]
		public System.Nullable<int> Num_Partida_Individual
		{
			get
			{
				return this._Num_Partida_Individual;
			}
			set
			{
				if ((this._Num_Partida_Individual != value))
				{
					this.OnNum_Partida_IndividualChanging(value);
					this.SendPropertyChanging();
					this._Num_Partida_Individual = value;
					this.SendPropertyChanged("Num_Partida_Individual");
					this.OnNum_Partida_IndividualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tbl_Partida_Individual_Tbl_Cargo_Institucional", Storage="_Tbl_Cargo_Institucional", ThisKey="Id_Partida_Individual", OtherKey="Id_Partida_Individual")]
		public EntitySet<Tbl_Cargo_Institucional> Tbl_Cargo_Institucional
		{
			get
			{
				return this._Tbl_Cargo_Institucional;
			}
			set
			{
				this._Tbl_Cargo_Institucional.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Tbl_Cargo_Institucional(Tbl_Cargo_Institucional entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Partida_Individual = this;
		}
		
		private void detach_Tbl_Cargo_Institucional(Tbl_Cargo_Institucional entity)
		{
			this.SendPropertyChanging();
			entity.Tbl_Partida_Individual = null;
		}
	}
	
	public partial class Listar_Estado_Activo_Cargo_InstitucionalResult
	{
		
		private int _Id_Cargo_Institucional;
		
		private string _Nom_Cargo_Institucional;
		
		private System.Nullable<int> _Numero_Partida_General;
		
		private System.Nullable<int> _Num_Partida_Individual;
		
		private string _Estado_Cargo_Institucional;
		
		public Listar_Estado_Activo_Cargo_InstitucionalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Cargo_Institucional", DbType="Int NOT NULL")]
		public int Id_Cargo_Institucional
		{
			get
			{
				return this._Id_Cargo_Institucional;
			}
			set
			{
				if ((this._Id_Cargo_Institucional != value))
				{
					this._Id_Cargo_Institucional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_Cargo_Institucional", DbType="VarChar(50)")]
		public string Nom_Cargo_Institucional
		{
			get
			{
				return this._Nom_Cargo_Institucional;
			}
			set
			{
				if ((this._Nom_Cargo_Institucional != value))
				{
					this._Nom_Cargo_Institucional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Partida_General", DbType="Int")]
		public System.Nullable<int> Numero_Partida_General
		{
			get
			{
				return this._Numero_Partida_General;
			}
			set
			{
				if ((this._Numero_Partida_General != value))
				{
					this._Numero_Partida_General = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Partida_Individual", DbType="Int")]
		public System.Nullable<int> Num_Partida_Individual
		{
			get
			{
				return this._Num_Partida_Individual;
			}
			set
			{
				if ((this._Num_Partida_Individual != value))
				{
					this._Num_Partida_Individual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Cargo_Institucional", DbType="VarChar(1)")]
		public string Estado_Cargo_Institucional
		{
			get
			{
				return this._Estado_Cargo_Institucional;
			}
			set
			{
				if ((this._Estado_Cargo_Institucional != value))
				{
					this._Estado_Cargo_Institucional = value;
				}
			}
		}
	}
	
	public partial class Listar_Estado_Activo_Partida_GeneralResult
	{
		
		private int _Id_Partida_General;
		
		private System.Nullable<int> _Numero_Partida_General;
		
		private string _Estado_Partida_General;
		
		public Listar_Estado_Activo_Partida_GeneralResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_General", DbType="Int NOT NULL")]
		public int Id_Partida_General
		{
			get
			{
				return this._Id_Partida_General;
			}
			set
			{
				if ((this._Id_Partida_General != value))
				{
					this._Id_Partida_General = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero_Partida_General", DbType="Int")]
		public System.Nullable<int> Numero_Partida_General
		{
			get
			{
				return this._Numero_Partida_General;
			}
			set
			{
				if ((this._Numero_Partida_General != value))
				{
					this._Numero_Partida_General = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Partida_General", DbType="VarChar(1)")]
		public string Estado_Partida_General
		{
			get
			{
				return this._Estado_Partida_General;
			}
			set
			{
				if ((this._Estado_Partida_General != value))
				{
					this._Estado_Partida_General = value;
				}
			}
		}
	}
	
	public partial class Listar_Partida_IndividualResult
	{
		
		private int _Id_Partida_Individual;
		
		private System.Nullable<int> _Num_Partida_Individual;
		
		public Listar_Partida_IndividualResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Partida_Individual", DbType="Int NOT NULL")]
		public int Id_Partida_Individual
		{
			get
			{
				return this._Id_Partida_Individual;
			}
			set
			{
				if ((this._Id_Partida_Individual != value))
				{
					this._Id_Partida_Individual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Partida_Individual", DbType="Int")]
		public System.Nullable<int> Num_Partida_Individual
		{
			get
			{
				return this._Num_Partida_Individual;
			}
			set
			{
				if ((this._Num_Partida_Individual != value))
				{
					this._Num_Partida_Individual = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
